# Site settings
title: Greg Garcia
email: gregorydgarcia@gmail.com
description: > 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gregorydgacia.github.io" # the base hostname & protocol for your site
twitter_username: gregorydgarcia
github_username:  gregorydgarcia

# Build settings
markdown: kramdown
